language: ruby

before_install: "gem install bones"
install:        "rake gem:install_dependencies"

script: "rake"

rvm:
  - 2.0.0-p648
  - 2.1.10
  - 2.2.7
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1  
  - jruby-9.2.6.0
